### ISSUE TITLE
No attribute `to_pydot`

### ISSUE THREAD

**Issue by Jesse-Millwood** [johnyf/pycflow2dot#2]
On Ubuntu 16.04, with `python3-pydot` and `python3-networkx` installed from `apt-get` the following message is emitted when running the example in the README: 
```
⤷ cflow2dot -i hello_simple.c -f png

    PyCflow2dot v0.1 - licensed under GNU GPL v3
    
found cflow at: /usr/bin/cflow
found dot at: /usr/bin/dot
Traceback (most recent call last):
  File "/usr/local/bin/cflow2dot", line 9, in <module>
    load_entry_point('pycflow2dot', 'console_scripts', 'cflow2dot')()
  File "/home/jesse/gitrepos/pycflow2dot/pycflow2dot.py", line 525, in main
    multi_page, layout)
  File "/home/jesse/gitrepos/pycflow2dot/pycflow2dot.py", line 360, in write_graphs2dot
    for_latex, multi_page, layout) ]
  File "/home/jesse/gitrepos/pycflow2dot/pycflow2dot.py", line 336, in write_graph2dot
    pydot_graph = nx.to_pydot(graph)
AttributeError: 'module' object has no attribute 'to_pydot'
```

**Comment by Jesse-Millwood** [comment]
The `.to_pydot` needs to be `.nx_pydot.to_pydot` (http://networkx.readthedocs.io/en/networkx-1.11/reference/generated/networkx.drawing.nx_pydot.to_pydot.html) at least for the 1.11 networkx version

**Comment by johnyf** [comment]
Thank you for reporting this bug, it was fixed recently on branch `dev` (baa03c05dbc3dbe2138257342f66790c471fc4d3).

**Comment by johnyf** [comment]
I released https://github.com/johnyf/pycflow2dot/releases/tag/v0.2.1 that includes this correction. Please note that it requires `networkx == 1.10` for the reasons described in 916bfbc83052a0f74b28e0b04b1e7c33c48d0f54. The upcoming `networkx` release reverts to using `pydot` (https://github.com/networkx/networkx/pull/2272), so `pycflow2dot` will work with `networkx > 1.11`.
